use std::io;
use std::path::Path;

/// Result of comparing generated output against an existing file.
#[derive(Debug, PartialEq)]
pub enum CheckResult {
    /// File exists and matches the generated output.
    Fresh,
    /// File exists but differs from the generated output.
    Stale,
    /// File does not exist.
    Missing,
}

/// Compare generated bytes against an existing file on disk.
///
/// Returns `Fresh` if the file exists and its contents match exactly,
/// `Stale` if the file exists but differs, and `Missing` if the file
/// does not exist. Other I/O errors (permissions, etc.) propagate.
pub fn check_freshness(generated: &[u8], path: &Path) -> io::Result<CheckResult> {
    match std::fs::read(path) {
        Ok(existing) => {
            if generated == existing.as_slice() {
                Ok(CheckResult::Fresh)
            } else {
                Ok(CheckResult::Stale)
            }
        }
        Err(e) if e.kind() == io::ErrorKind::NotFound => Ok(CheckResult::Missing),
        Err(e) => Err(e),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn fresh_when_file_matches() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("output.md");
        let content = b"stateDiagram-v2\n  [*] --> entry\n";
        fs::write(&path, content).unwrap();

        let result = check_freshness(content, &path).unwrap();
        assert_eq!(result, CheckResult::Fresh);
    }

    #[test]
    fn stale_when_file_differs() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("output.md");
        fs::write(&path, b"old content").unwrap();

        let result = check_freshness(b"new content", &path).unwrap();
        assert_eq!(result, CheckResult::Stale);
    }

    #[test]
    fn missing_when_file_does_not_exist() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("nonexistent.md");

        let result = check_freshness(b"anything", &path).unwrap();
        assert_eq!(result, CheckResult::Missing);
    }

    #[test]
    fn io_error_propagates() {
        // Attempting to read a directory as a file produces an I/O error
        // on most platforms.
        let dir = tempfile::tempdir().unwrap();
        let result = check_freshness(b"data", dir.path());
        assert!(result.is_err());
    }
}
